// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { env } from './config/env';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: `postgresql://${env.DB_USER}:${env.DB_PASSWORD}@${env.DB_HOST}:${env.DB_PORT}/${env.DB_DATABASE}`,
  },
});
